bootstrapping_rails/config/routes.rb
Rails.application.routes.draw do
  get '/whatever' => 'whatever#hello', as: :human
  get '/whatever2' => 'whatever2#giphy', as: :hello
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bootstrapping_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bootstrapping_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bootstrapping_rails/app/controllers/whatever2_controller.rb
class Whatever2Controller < ApplicationController
  def giphy
    @howdy = "Howdy human"
  end
end

bootstrapping_rails/app/controllers/whatever_controller.rb
class WhateverController < ApplicationController
  def hello
    @hi = "Hello world"
  end
end

bootstrapping_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

bootstrapping_rails/app/helpers/whatever2_helper.rb
module Whatever2Helper
end

bootstrapping_rails/app/helpers/whatever_helper.rb
module WhateverHelper
end

bootstrapping_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>BootstrappingRails</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </head>

    <body>
        <%= yield %>
    </body>
</html>

bootstrapping_rails/app/views/whatever/hello.html.erb
<h1><%=@hi%></h1>
<%= link_to "Human", hello_path%>
<div class = "container text-center">
  <%= image_tag("suarez") %>
  <p>Gooooooooooool!!</p>
</div>

bootstrapping_rails/app/views/whatever2/giphy.html.erb
<h2><%=@howdy%></h2>
<%= link_to "Hello Word", human_path%>
<div class = "container text-center">
  <%= image_tag("messi") %>
  <p>Is he human?</p>
</div>